POST http://localhost:4000/create-link
Content-Type: application/json

{
    "url" : "https://github.com/goutham469/url-shortener/tree/server",
    "api":false
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email":"gouth@gmail.com"
}